(ql:quickload :uiop)
(ql:quickload :str)
(ql:quickload :arrow-macros)
(use-package :arrow-macros)

(defpackage AoC-2015-07
  (:use :cl))

(in-package :AoC-2015-07)

(defun get-test-input ()
  (uiop:read-file-lines "input/day-07-test.txt"))

(defun get-input ()
  (uiop:read-file-lines "input/day-07.txt"))

(defun parse-line (line)
  (let* ((line (str:split " -> " line))
         (ops (str:words (car line)))
         (ops-len (length ops))
         (wire (cadr line)))
    (list :op (cond ((= ops-len 3) (get-op (read-from-string (second ops))))
                    ((= ops-len 2) (get-op (read-from-string (first ops))))
                    (t nil))
          :arg1 (let ((arg (if (= ops-len 2)
                               (second ops)
                               (first ops))))
                  (if (every #'digit-char-p arg)
                      (parse-integer arg)
                      (read-from-string arg)))
          :arg2 (if (= ops-len 3)
                    (if (every #'digit-char-p (third ops))
                        (parse-integer (third ops))
                        (read-from-string (third ops)))
                    nil)
          :wire (read-from-string wire))))

(defun get-op (op)
  (cond ((eq op 'and) #'logand)
        ((eq op 'or) #'logior)
        ((eq op 'lshift) #'ash)
        ((eq op 'rshift) #'(lambda (a b) (ash a (- b))))
        ((eq op 'not) #'(lambda (a) (logand (lognot a) #xFFFF)))))

(defun solve-1 (input)
  (let ((circuit (make-hash-table))
        (resolved (make-hash-table)))
    (loop for line in input
          for instr = (parse-line line)
          do (setf (gethash (getf instr :wire) circuit) instr))
    (labels ((resolve (wire-or-val)
               (cond ((integerp wire-or-val) wire-or-val)
                     ((gethash wire-or-val resolved) (gethash wire-or-val resolved))
                     (t (let* ((instr (gethash wire-or-val circuit))
                               (op (getf instr :op))
                               (arg1 (getf instr :arg1))
                               (arg2 (getf instr :arg2))
                               (val (cond ((and op arg2) (funcall op (resolve arg1) (resolve arg2)))
                                          (op (funcall op (resolve arg1)))
                                          (t (resolve arg1)))))
                          (setf (gethash wire-or-val resolved) val)
                          val)))))
      (resolve 'a))))

(defun solve-2 (input)
  (let ((signal-a (solve-1 input)))
    ;; bygg om instruktionslistan: ersätt b:s instruktion med en konstant
    (let ((new-input
            (mapcar (lambda (line)
                      (if (str:ends-with-p " -> b" line)
                          (format nil "~a -> b" signal-a)
                          line))
                    input)))
      (solve-1 new-input))))
